### ISSUE TITLE
Supervise an already running actor.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid-supervision#16]
Right now the supervision container itself instantiates the actor.

An already running actor ought to be possible to supervise once it's already instantiated.

... possibly requiring the saving of the initialization parameters.

**Comment by tarcieri** [comment]
If you try to supervise an actor after it's been started, how do you prevent races involving the actor dying before the supervisor starts?

Sure you can potentially detect that, but why add the extra complexity? What's the use case?

Supervision is a place where you have to be very, very, very, very, very careful about what you do, because it's extremely easy to create racy code, and extremely hard to know if your implementation is robust. This is why I have been reluctant to add features to supervision in general.

In general I would suggest shoring up the existing supervision implementation and making sure it's rock solid before adding additional features, and if you do want to add additional features, you might want to first:

1) look for precedent in Erlang and/or Akka
2) make sure there's a clear, well-defined use case
3) do a complete flow diagram of all of the potential temporal interactions between actors, and make sure they aren't racy

#3 is the hardest. These are the kinds of problems that are best modeled in terms of temporal logic, with model checking.

In the absence of that, your best bet is to keep things simple.

**Comment by benlangfeld** [comment]
I don't think this should be implemented until someone can properly defend "ought to be possible". Use-case first would be a good idea :)

**Comment by digitalextremist** [comment]
I've been looking for precedent in Erlang and Akka. That in and of itself has been interesting and will probably lead to bringing over some ideas, like `one_for_one`, `one_for_all`, `rest_for_one` behaviors. I expect to work on bullet-proofing supervision before spending time on anything experimental like this. 

The use cases are not that significant or urgent if at all. The @tarcieri caution regarding race conditions is closely felt, but the @benlangfeld comment seems like a challenge... I ... can't... resist... :)

**Comment by tarcieri** [comment]
Supervising after-the-fact just seems backwards to me. I'd say don't do it unless there's a *good* use case.

**Comment by digitalextremist** [comment]
No use case justifies this for the foreseeable future.
