### ISSUE TITLE
Cannot #supervise_as() any Actor with a mix of required and optional arguments to its constructor.

### ISSUE THREAD

**Issue by clonezone** [celluloid/celluloid-supervision#22]
The condition in [`Celluloid::Supervision::Configuration.valid?()`](https://github.com/celluloid/celluloid-supervision/blob/6cc9c38e7285b8b717ae3513dd91d14c7cbea579/lib/celluloid/supervision/validation.rb#L19) prevents supervising Actors with some required and some optional arguments, specifically, in my case `Reel::Server::HTTP`, because the arity of `Reel::Server::HTTP#initialize()` is -3.

**Comment by digitalextremist** [comment]
I've noticed this too and I'll get back on fixing it.

**Comment by digitalextremist** [comment]
@clonezone go ahead and try that... and make sure you use the new API to be compatible with new releases... so your call would be:

```
ActorClass.supervise as: :name, args: []
```

**Comment by clonezone** [comment]
You can't just flip the sign of the [return value of `#arity()`](http://ruby-doc.org/core-2.2.2/Method.html#method-i-arity). You need to subtract one from the absolute value, if it is negative.

**Comment by digitalextremist** [comment]
I did make one mistake, but not what I think you are saying. I had switched who was checked against who. I changed it to this:

```
(__arity < 0 && __a <= __arity.abs) || __a == __arity
```

Here's the logic... if you are giving the configuration something like this:
```
args: [ hostname, port, options_hash ]
```
Then `__a == __arity.abs` is true...`3 vs. 3`

But that'd be affirmed by this instead:

`__arity <= 0` ... true ( that'd be `-3` vs. 0 )
`__a <= __arity.abs` ( that'd be 3 vs. 3 )


But if you passed in `args: [ host, port ]` only, with no options hash, it'd be:

`__a == __arity.abs` is false...`2 vs. 3` ... but we wouldn't get that far.

It'd be affirmed by this instead:

`__arity <= 0` ... true ( that'd be `-3` vs. 0 )
`__a <= __arity.abs` ( that'd be 2 vs. 3 )

But now that I rubberduckie this... I think you're saying this:

It needs to instead be:

```
unless (__arity < 0 && __a >= __arity.abs-1) || __a == __arity.abs
```

Because the first two parameters *are* required. `1` arity would pass my condition, but be incorrect.



Correct?

**Comment by digitalextremist** [comment]
@clonezone is this working for you now?

**Comment by clonezone** [comment]
Not directly out of the repository. If I add `gem 'celluloid-supervision', git: 'https://github.com/celluloid/celluloid-supervision.git'` to my Gemfile, bundler gets a LoadError on line 3 of `celluloid-supervision.gemspec` with the message "Does it try to require a relative path? That's been removed in Ruby 1.9."

**Comment by digitalextremist** [comment]
It needs `submodules: true` ... but `celluloid-supervision` is already brought in by `celluloid` itself currently.

**Comment by clonezone** [comment]
Ok, after a bunch of screwing around with setup, I can get my app up with master celluloid with an override of master celluloid-supervision. So, once this gets properly released, I'll be able to move off of v0.16.

**Comment by digitalextremist** [comment]
I just issued a point release of `0.20.1` of this gem.

**Comment by clonezone** [comment]
v0.20.1 does not work with celluloid v0.17.0.

"uninitialized constant Celluloid::Actor::System" at celluloid/supervision/container/instance.rb:100.

**Comment by digitalextremist** [comment]
Are you doing `celluloid/current`? Either way I'll have deprecated.rb load sooner and rerelease.

**Comment by clonezone** [comment]
Nope. As the first step of porting, just leaving everything as it is. Once I've got that going, then I can start work on getting the code modernized.

**Comment by digitalextremist** [comment]
Then I'll push a `0.17.1` point release of `Celluloid` itself to cover this.

**Comment by digitalextremist** [comment]
`0.17.1` cut with deprecate coverage for what you mentioned.

**Comment by clonezone** [comment]
That works fine.

Thank you for all your help.

**Comment by digitalextremist** [comment]
That's what I'm here for -- very glad you're moving ahead. I'll close this and watch for the next thing you hit as you modernize.
